FROM kollaglue/fedora-rdo-glance-base
MAINTAINER Kolla Project (https://launchpad.net/kolla)

# Add startup script
ADD ./start.sh /opt/kolla/start.sh

# Run startup script
CMD ["/opt/kolla/start.sh"]
