#FROM kollaglue/fedora-rdo-glance-base
#MAINTAINER Dan Radez <dradez@redhat.com>
FROM danehans/fedora-rdo-glance-base
MAINTAINER Daneyon Hansen <danehans@cisco.com>

ADD ./start.sh /start.sh
CMD ["/start.sh"]

