#!/bin/bash
if [[ $EUID -ne 0 ]]; then
    echo "You must execute this script as root." 1>&2
    exit 1
fi

# Move to top level directory
REAL_PATH=$(python -c "import os,sys;print os.path.realpath('$0')")
cd "$(dirname "$REAL_PATH")/.."

# Source openrc for commands
source ./openrc

for i in "L3 agent" "Metadata agent" "Linux bridge agent" "DHCP agent" 
do
   neutron agent-list | grep i | awk '{print $10;}' 
   echo "Agent up"
done
