#!/bin/bash
if [[ $EUID -ne 0 ]]; then
    echo "You must execute this script as root." 1>&2
    exit 1
fi

# Move to top level directory
REAL_PATH=$(python -c "import os,sys;print os.path.realpath('$0')")
cd "$(dirname "$REAL_PATH")/.."

netns_list=(ip netns list)
for i in $netns_list
do
   ip netns delete $i 
   echo "Deleted netns $i"
done
