#!/bin/bash
if [[ $EUID -ne 0 ]]; then
    echo "You must execute this script as root." 1>&2
    exit 1
fi

# Move to top level directory
REAL_PATH=$(python -c "import os,sys;print os.path.realpath('$0')")
cd "$(dirname "$REAL_PATH")/.."

#mysql -h192.168.220.52 -uroot -pkolla -e "drop database neutron;"

ip netns list | while read -r line ; do
  ip netns delete $line
done

ifconfig | grep tap | awk '{print $1;}'| cut -f1 -d':' | while read -r line ; do
  ip link delete $line type veth
done

ifconfig | grep brq | awk '{print $1;}'| cut -f1 -d':' | while read -r line ; do
  ip link delete $line type bridge
done

ifconfig | grep vxlan | awk '{print $1;}'| cut -f1 -d':' | while read -r line ; do
  ip link delete $line type vxlan
done
